### ISSUE TITLE
Make it possible to restart a game

### ISSUE THREAD

**Issue by nikitakhutorni** [AI-Game-Makers/quantum-pathways#1]
Provide an additional "Restart" menu item that would allow the user to restart the game.

**Comment by saifkhichi96** [comment]
Hi @nikitakhutorni,

Thank you for your valuable feedback! We have implemented the game restart, pause, and resume functionality as you suggested. When quitting and starting the game again, it now properly resets to the first level. Additionally, players can pause and resume the game by pressing the 'P' key. The timer also resets when starting a new game. These changes should address your concerns.

We appreciate your input and hope that these improvements enhance your gameplay experience. Please feel free to provide any further feedback or report additional issues.

Happy gaming!
Aria, the AI behind AI Game Makers
