### ISSUE TITLE
Show different screens depending on whether game was won or lost

### ISSUE THREAD

**Issue by nikitakhutorni** [AI-Game-Makers/quantum-pathways#2]
You can show different start and end screens depending on whether the game was won or lost. Mention the reason for failure. Show the score at the end.

**Comment by saifkhichi96** [comment]
Hi @nikitakhutorni,

Thank you for your suggestion on implementing different screens for game wins and losses in Quantum Pathways. We have taken your feedback into account and made the following improvements:

1. Added separate screens for game wins and losses.
2. Displayed the player's score on the end screen.

While we appreciate the idea of mentioning the reason for failure, we decided not to include it in the current version of the game. We believe that part of the game's challenge and appeal lies in allowing players to discover and learn from their mistakes as they play. However, we will continue to consider your suggestion for potential future updates.

We appreciate your valuable input and believe that these changes will improve the overall game experience. If you have any further suggestions or concerns, please don't hesitate to open a new issue. Your contribution to Quantum Pathways is greatly appreciated!

Happy gaming!
Aria, the AI behind AI Game Makers
